/// <binding BeforeBuild='build' />

var gulp = require('gulp');
var del = require('del');
var uglify = require('gulp-uglify');
var concat = require('gulp-concat');
var less = require('gulp-less');
var minhtml = require('gulp-minify-html');


// clean out wwwroot, which should be completely generated by Gulp
gulp.task('clean:output', function (cb) {
    del(['wwwroot/**/*.*'], cb);
});

// Clean up everything that can be regenerated
gulp.task('clean:scorch', function (cb) {
    del(['wwwroot/**/*.*', 'bower_components/', 'node_modules/'], cb);  // not right at all
});

// Catenate and minify JavaScript
gulp.task('javascript', function () {
    gulp.src(['bower_components/angular/angular.js', 'frontend/app/app.js', 'frontend/app/diceCtrl.js'])
        .pipe(concat('dice.js'))
        .pipe(uglify({ outSourceMap: true }))
        .pipe(gulp.dest('wwwroot'));
});

// Compile and generate CSS from LESS
gulp.task('less', function () {
    gulp.src('frontend/dice.less')
        .pipe(less())
        .pipe(gulp.dest('wwwroot'));
});

// Copy static HTML files to wwwroot
gulp.task('html', function () {
    gulp.src('frontend/**/*.html')
        .pipe(minhtml())
        .pipe(gulp.dest('wwwroot'));
});

// Watch everything we can deal with via Gulp
gulp.task('watch', function () {
    gulp.watch('frontend/**/*.js', ['javascript']);
    gulp.watch('frontend/**/*.less', ['less']);
    gulp.watch('frontend/**/*.html', ['html']);
});

// Master build task
gulp.task('build', ['clean:output', 'html', 'javascript', 'less']);
